global:
  scrape_interval: 3s

scrape_configs:
  - job_name: 'virtual-threads-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['virtual-threads-app:8080']

  - job_name: 'webflux-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['webflux-app:8080']